-- =======================================================
-- SQL Schema for Magic Scale AR (เครื่องชั่งมหัศจรรย์ AR)
-- Platform: Supabase (PostgreSQL)
-- =======================================================

-- 1. Create Leaderboard Table
create table if not exists public.leaderboard (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    session_id text default '',
    player_name text not null,
    score bigint default 0 not null,
    highest_level integer default 1 not null,
    correct_answers integer default 0 not null,
    wrong_attempts integer default 0 not null,
    play_time integer default 0 not null
);

-- 2. Create Indexes for High-Performance Queries
create index if not exists idx_leaderboard_score_time 
on public.leaderboard (score desc, play_time asc);

create index if not exists idx_leaderboard_player_name 
on public.leaderboard (player_name);

-- 3. Enable Row Level Security (RLS)
alter table public.leaderboard enable row level security;

-- 4. Create Security Policies (Allow Public Read & Write for Game Client)
-- Allow anyone to view the leaderboard
drop policy if exists "Allow public read access" on public.leaderboard;
create policy "Allow public read access"
on public.leaderboard for select
to anon, authenticated
using (true);

-- Allow players to insert their scores
drop policy if exists "Allow public insert access" on public.leaderboard;
create policy "Allow public insert access"
on public.leaderboard for insert
to anon, authenticated
with check (true);
